CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS agent;

ALTER TABLE IF EXISTS market.watchlist_items
  DROP COLUMN IF EXISTS latest_price,
  DROP COLUMN IF EXISTS change_pct;

ALTER TABLE IF EXISTS market.stock_instruments
  DROP COLUMN IF EXISTS latest_price,
  DROP COLUMN IF EXISTS change_pct;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'market_app') THEN
    GRANT USAGE ON SCHEMA market TO market_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA market TO market_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA market TO market_app;
    ALTER DEFAULT PRIVILEGES IN SCHEMA market
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO market_app;
    ALTER DEFAULT PRIVILEGES IN SCHEMA market
      GRANT USAGE, SELECT ON SEQUENCES TO market_app;
  END IF;
END
$$;
