ALTER TABLE market.stock_quote_snapshots
  ADD COLUMN IF NOT EXISTS turnover_rate DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS amount DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS float_market_cap DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS total_market_cap DOUBLE PRECISION;
